### ISSUE TITLE
Naming diff in DefaultBranchProtectionDefaults

### ISSUE THREAD

**Issue by breuerfelix** [pulumi/pulumi-gitlab#727]
With PR #717 the field `gitlab.Group.defaultBranchProtectionDefaults` was introduced.

I think that the following sub-field names are not valid English:

```
allowedToPushes: [],
allowedToMerges: [],
```

Why do these differ from the [original](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group#default_branch_protection_defaults) terraform naming?

```
allowed_to_push  = []
allowed_to_merge = []
```

/cc @flubbes

**Comment by guineveresaenger** [comment]
Hi @breuerfelix - Pulumi resources are pluralized when the underlying object or type is a collection, as is the case here.

As for the English validity, this is a matter of opinion and taste. I'm not a linguist, but neither is the compiler, so you may rest assured that this field will work as advertised.

Since you're not mentioning any out-of-spec behavior, I'm going to close this issue.

**Comment by breuerfelix** [comment]
Hey @guineveresaenger, thanks for the response.

I understand that this is a compiler decision right here and I am aware that the variables won't get changed. This is fine for me.

Just out of curiosity, is there any ADR or written documentation on why this decision was made to pluralise resources if the underlying object is a collection?
I would assume that the upstream maintainers (in this case terraform) would correctly name the variable since they also know that the underlying resource is a collection. And if they decide to not pluralise the name, this might have a good reason.
